# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: A Starter of Physics
author: ivaquero
copyright: '2022'
logo: doge.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, '**.ipynb_checkpoints']
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout: 500
  allow_errors: false
  stderr_output: show

# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
  myst_url_schemes: [mailto, http, https]
  myst_dmath_double_inline: true

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: 'xelatex'
  latex_documents:
    targetname: book.tex
  use_jupyterbook_latex: true

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: doge.png
  baseurl: 'https://ivaquero.github.io/blog-physics/'
  extra_footer: '' # Will be displayed underneath the footer.
  home_page_in_navbar: true # Whether to include your home page in the left Navigation Bar
  navbar_number_sections: false # Add a number to each section in your left navbar
  use_edit_page_button: false # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_issues_button: false # Whether to add an "open an issue" button
  use_repository_button: false # Whether to add a link to your repository button
  use_multitoc_numbering: true # Continuous numbering across parts/chapters

# Information about where the book exists on the web
repository:
  url: https://github.com/ivaquero/blog-physics/ # Online location of your book
  path_to_book: '' # Optional path to your book, relative to the repository root
  branch: master # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: jupyterlab
  tojupyter_images_markdown: true
  tojupyter_target_html: true
  tojupyter_default_lang: julia
  tojupyter_lang_synonyms: ['julia-1.6']
  tojupyter_kernels:
    julia:
      kernelspec:
        display_name: Julia
        language: julia
        name: julia-1.6
